name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: actions/setup-python@v6.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: false
      - name: Run integration tests
        run: ./scripts/run_integration_tests.sh
